version: "3"

services:
  postgres:
    image: postgres:14.0
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: airflowuser
      POSTGRES_PASSWORD: airflowpassword
      POSTGRES_DB: airflowdb
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "airflowuser", "-d", "airflowdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  initdb:
    image: simple-dataops-airflow:latest
    container_name: initdb
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init &&
        airflow users create --firstname admin --lastname admin --email admin --password admin --username admin --role Admin

  webserver:
    image: simple-dataops-airflow:latest
    container_name: webserver
    depends_on:
      - initdb
    env_file:
      - .env
    ports:
      - 8080:8080
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 10s
      retries: 3

  scheduler:
    image: simple-dataops-airflow:latest
    container_name: scheduler
    depends_on:
      - webserver
    env_file:
      - .env
    command: scheduler

  flower:
    image: simple-dataops-airflow:latest
    container_name: flower
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - 5555:5555
    command: celery flower

  worker1:
    image: simple-dataops-airflow:latest
    container_name: worker1
    depends_on:
      - scheduler
    env_file:
      - .env
    command: celery worker -H worker1 -q queue1

  worker2:
    image: simple-dataops-airflow:latest
    container_name: worker2
    depends_on:
      - scheduler
    env_file:
      - .env
    command: celery worker -H worker2 -q queue2

  worker3:
    image: simple-dataops-airflow:latest
    container_name: worker3
    depends_on:
      - scheduler
    env_file:
      - .env
    command: celery worker -H worker3 -q queue3
