version: "3"

services:
  redis:
    image: redis:7.0
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  data-generator:
    build:
      context: docker/data-generator
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
