version: "3"

services:
  redis-server:
    image: redis/redis-stack
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # data-generator:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     redis:
  #       condition: service_healthy

networks:
  default:
    name: redis-networks
