name: "[Repo CI] Docker Image"

on:
  push:
    branches: [ feature/add-docker-image-github-action ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        load: true
        tags: simple-dataops-airflow:latest
